[project]
authors = ["Elek <elek>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "CUDA_cli"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fastapi = ">=0.128.0,<0.129"
uvicorn = ">=0.40.0,<0.41"
pillow = ">=12.1.0,<13"
streamlit = ">=1.52.2,<2"

[pypi-dependencies]
streamlit-image-coordinates = ">=0.4.0, <0.5"
